

#pragma once

#ifndef GO_MOC_3419f1_H
#define GO_MOC_3419f1_H

#include <stdint.h>

#ifdef __cplusplus
class PersonModel3419f1;
void PersonModel3419f1_PersonModel3419f1_QRegisterMetaTypes();
class QmlBridge3419f1;
void QmlBridge3419f1_QmlBridge3419f1_QRegisterMetaTypes();
class Person3419f1;
void Person3419f1_Person3419f1_QRegisterMetaTypes();
extern "C" {
#endif

struct Moc_PackedString { char* data; long long len; void* ptr; };
struct Moc_PackedList { void* data; long long len; };
struct Moc_PackedString Person3419f1_Id(void* ptr);
struct Moc_PackedString Person3419f1_IdDefault(void* ptr);
void Person3419f1_SetId(void* ptr, struct Moc_PackedString id);
void Person3419f1_SetIdDefault(void* ptr, struct Moc_PackedString id);
void Person3419f1_ConnectIdChanged(void* ptr, long long t);
void Person3419f1_DisconnectIdChanged(void* ptr);
void Person3419f1_IdChanged(void* ptr, struct Moc_PackedString id);
struct Moc_PackedString Person3419f1_FirstName(void* ptr);
struct Moc_PackedString Person3419f1_FirstNameDefault(void* ptr);
void Person3419f1_SetFirstName(void* ptr, struct Moc_PackedString firstName);
void Person3419f1_SetFirstNameDefault(void* ptr, struct Moc_PackedString firstName);
void Person3419f1_ConnectFirstNameChanged(void* ptr, long long t);
void Person3419f1_DisconnectFirstNameChanged(void* ptr);
void Person3419f1_FirstNameChanged(void* ptr, struct Moc_PackedString firstName);
struct Moc_PackedString Person3419f1_LastName(void* ptr);
struct Moc_PackedString Person3419f1_LastNameDefault(void* ptr);
void Person3419f1_SetLastName(void* ptr, struct Moc_PackedString lastName);
void Person3419f1_SetLastNameDefault(void* ptr, struct Moc_PackedString lastName);
void Person3419f1_ConnectLastNameChanged(void* ptr, long long t);
void Person3419f1_DisconnectLastNameChanged(void* ptr);
void Person3419f1_LastNameChanged(void* ptr, struct Moc_PackedString lastName);
int Person3419f1_Person3419f1_QRegisterMetaType();
int Person3419f1_Person3419f1_QRegisterMetaType2(char* typeName);
int Person3419f1_Person3419f1_QmlRegisterType();
int Person3419f1_Person3419f1_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
int Person3419f1_Person3419f1_QmlRegisterUncreatableType(char* uri, int versionMajor, int versionMinor, char* qmlName, struct Moc_PackedString message);
void* Person3419f1___children_atList(void* ptr, int i);
void Person3419f1___children_setList(void* ptr, void* i);
void* Person3419f1___children_newList(void* ptr);
void* Person3419f1___dynamicPropertyNames_atList(void* ptr, int i);
void Person3419f1___dynamicPropertyNames_setList(void* ptr, void* i);
void* Person3419f1___dynamicPropertyNames_newList(void* ptr);
void* Person3419f1___findChildren_atList(void* ptr, int i);
void Person3419f1___findChildren_setList(void* ptr, void* i);
void* Person3419f1___findChildren_newList(void* ptr);
void* Person3419f1___findChildren_atList3(void* ptr, int i);
void Person3419f1___findChildren_setList3(void* ptr, void* i);
void* Person3419f1___findChildren_newList3(void* ptr);
void* Person3419f1_NewPerson(void* parent);
void Person3419f1_DestroyPerson(void* ptr);
void Person3419f1_DestroyPersonDefault(void* ptr);
void Person3419f1_ChildEventDefault(void* ptr, void* event);
void Person3419f1_ConnectNotifyDefault(void* ptr, void* sign);
void Person3419f1_CustomEventDefault(void* ptr, void* event);
void Person3419f1_DeleteLaterDefault(void* ptr);
void Person3419f1_DisconnectNotifyDefault(void* ptr, void* sign);
char Person3419f1_EventDefault(void* ptr, void* e);
char Person3419f1_EventFilterDefault(void* ptr, void* watched, void* event);
;
void Person3419f1_TimerEventDefault(void* ptr, void* event);
void PersonModel3419f1_AddPerson(void* ptr, void* v0);
void PersonModel3419f1_EditPerson(void* ptr, int row, struct Moc_PackedString firstName, struct Moc_PackedString lastName);
void PersonModel3419f1_RemovePerson(void* ptr, int row);
struct Moc_PackedList PersonModel3419f1_Roles(void* ptr);
struct Moc_PackedList PersonModel3419f1_RolesDefault(void* ptr);
void PersonModel3419f1_SetRoles(void* ptr, void* roles);
void PersonModel3419f1_SetRolesDefault(void* ptr, void* roles);
void PersonModel3419f1_ConnectRolesChanged(void* ptr, long long t);
void PersonModel3419f1_DisconnectRolesChanged(void* ptr);
void PersonModel3419f1_RolesChanged(void* ptr, void* roles);
struct Moc_PackedList PersonModel3419f1_People(void* ptr);
struct Moc_PackedList PersonModel3419f1_PeopleDefault(void* ptr);
void PersonModel3419f1_SetPeople(void* ptr, void* people);
void PersonModel3419f1_SetPeopleDefault(void* ptr, void* people);
void PersonModel3419f1_ConnectPeopleChanged(void* ptr, long long t);
void PersonModel3419f1_DisconnectPeopleChanged(void* ptr);
void PersonModel3419f1_PeopleChanged(void* ptr, void* people);
int PersonModel3419f1_PersonModel3419f1_QRegisterMetaType();
int PersonModel3419f1_PersonModel3419f1_QRegisterMetaType2(char* typeName);
int PersonModel3419f1_PersonModel3419f1_QmlRegisterType();
int PersonModel3419f1_PersonModel3419f1_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
int PersonModel3419f1_PersonModel3419f1_QmlRegisterUncreatableType(char* uri, int versionMajor, int versionMinor, char* qmlName, struct Moc_PackedString message);
int PersonModel3419f1_____itemData_keyList_atList(void* ptr, int i);
void PersonModel3419f1_____itemData_keyList_setList(void* ptr, int i);
void* PersonModel3419f1_____itemData_keyList_newList(void* ptr);
int PersonModel3419f1_____roleNames_keyList_atList(void* ptr, int i);
void PersonModel3419f1_____roleNames_keyList_setList(void* ptr, int i);
void* PersonModel3419f1_____roleNames_keyList_newList(void* ptr);
int PersonModel3419f1_____setItemData_roles_keyList_atList(void* ptr, int i);
void PersonModel3419f1_____setItemData_roles_keyList_setList(void* ptr, int i);
void* PersonModel3419f1_____setItemData_roles_keyList_newList(void* ptr);
void* PersonModel3419f1___changePersistentIndexList_from_atList(void* ptr, int i);
void PersonModel3419f1___changePersistentIndexList_from_setList(void* ptr, void* i);
void* PersonModel3419f1___changePersistentIndexList_from_newList(void* ptr);
void* PersonModel3419f1___changePersistentIndexList_to_atList(void* ptr, int i);
void PersonModel3419f1___changePersistentIndexList_to_setList(void* ptr, void* i);
void* PersonModel3419f1___changePersistentIndexList_to_newList(void* ptr);
int PersonModel3419f1___dataChanged_roles_atList(void* ptr, int i);
void PersonModel3419f1___dataChanged_roles_setList(void* ptr, int i);
void* PersonModel3419f1___dataChanged_roles_newList(void* ptr);
void* PersonModel3419f1___itemData_atList(void* ptr, int v, int i);
void PersonModel3419f1___itemData_setList(void* ptr, int key, void* i);
void* PersonModel3419f1___itemData_newList(void* ptr);
struct Moc_PackedList PersonModel3419f1___itemData_keyList(void* ptr);
void* PersonModel3419f1___layoutAboutToBeChanged_parents_atList(void* ptr, int i);
void PersonModel3419f1___layoutAboutToBeChanged_parents_setList(void* ptr, void* i);
void* PersonModel3419f1___layoutAboutToBeChanged_parents_newList(void* ptr);
void* PersonModel3419f1___layoutChanged_parents_atList(void* ptr, int i);
void PersonModel3419f1___layoutChanged_parents_setList(void* ptr, void* i);
void* PersonModel3419f1___layoutChanged_parents_newList(void* ptr);
void* PersonModel3419f1___match_atList(void* ptr, int i);
void PersonModel3419f1___match_setList(void* ptr, void* i);
void* PersonModel3419f1___match_newList(void* ptr);
void* PersonModel3419f1___mimeData_indexes_atList(void* ptr, int i);
void PersonModel3419f1___mimeData_indexes_setList(void* ptr, void* i);
void* PersonModel3419f1___mimeData_indexes_newList(void* ptr);
void* PersonModel3419f1___persistentIndexList_atList(void* ptr, int i);
void PersonModel3419f1___persistentIndexList_setList(void* ptr, void* i);
void* PersonModel3419f1___persistentIndexList_newList(void* ptr);
void* PersonModel3419f1___roleNames_atList(void* ptr, int v, int i);
void PersonModel3419f1___roleNames_setList(void* ptr, int key, void* i);
void* PersonModel3419f1___roleNames_newList(void* ptr);
struct Moc_PackedList PersonModel3419f1___roleNames_keyList(void* ptr);
void* PersonModel3419f1___setItemData_roles_atList(void* ptr, int v, int i);
void PersonModel3419f1___setItemData_roles_setList(void* ptr, int key, void* i);
void* PersonModel3419f1___setItemData_roles_newList(void* ptr);
struct Moc_PackedList PersonModel3419f1___setItemData_roles_keyList(void* ptr);
int PersonModel3419f1_____doSetRoleNames_roleNames_keyList_atList(void* ptr, int i);
void PersonModel3419f1_____doSetRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* PersonModel3419f1_____doSetRoleNames_roleNames_keyList_newList(void* ptr);
int PersonModel3419f1_____setRoleNames_roleNames_keyList_atList(void* ptr, int i);
void PersonModel3419f1_____setRoleNames_roleNames_keyList_setList(void* ptr, int i);
void* PersonModel3419f1_____setRoleNames_roleNames_keyList_newList(void* ptr);
void* PersonModel3419f1___children_atList(void* ptr, int i);
void PersonModel3419f1___children_setList(void* ptr, void* i);
void* PersonModel3419f1___children_newList(void* ptr);
void* PersonModel3419f1___dynamicPropertyNames_atList(void* ptr, int i);
void PersonModel3419f1___dynamicPropertyNames_setList(void* ptr, void* i);
void* PersonModel3419f1___dynamicPropertyNames_newList(void* ptr);
void* PersonModel3419f1___findChildren_atList(void* ptr, int i);
void PersonModel3419f1___findChildren_setList(void* ptr, void* i);
void* PersonModel3419f1___findChildren_newList(void* ptr);
void* PersonModel3419f1___findChildren_atList3(void* ptr, int i);
void PersonModel3419f1___findChildren_setList3(void* ptr, void* i);
void* PersonModel3419f1___findChildren_newList3(void* ptr);
void* PersonModel3419f1___roles_atList(void* ptr, int v, int i);
void PersonModel3419f1___roles_setList(void* ptr, int key, void* i);
void* PersonModel3419f1___roles_newList(void* ptr);
struct Moc_PackedList PersonModel3419f1___roles_keyList(void* ptr);
void* PersonModel3419f1___setRoles_roles_atList(void* ptr, int v, int i);
void PersonModel3419f1___setRoles_roles_setList(void* ptr, int key, void* i);
void* PersonModel3419f1___setRoles_roles_newList(void* ptr);
struct Moc_PackedList PersonModel3419f1___setRoles_roles_keyList(void* ptr);
void* PersonModel3419f1___rolesChanged_roles_atList(void* ptr, int v, int i);
void PersonModel3419f1___rolesChanged_roles_setList(void* ptr, int key, void* i);
void* PersonModel3419f1___rolesChanged_roles_newList(void* ptr);
struct Moc_PackedList PersonModel3419f1___rolesChanged_roles_keyList(void* ptr);
void* PersonModel3419f1___people_atList(void* ptr, int i);
void PersonModel3419f1___people_setList(void* ptr, void* i);
void* PersonModel3419f1___people_newList(void* ptr);
void* PersonModel3419f1___setPeople_people_atList(void* ptr, int i);
void PersonModel3419f1___setPeople_people_setList(void* ptr, void* i);
void* PersonModel3419f1___setPeople_people_newList(void* ptr);
void* PersonModel3419f1___peopleChanged_people_atList(void* ptr, int i);
void PersonModel3419f1___peopleChanged_people_setList(void* ptr, void* i);
void* PersonModel3419f1___peopleChanged_people_newList(void* ptr);
int PersonModel3419f1_____roles_keyList_atList(void* ptr, int i);
void PersonModel3419f1_____roles_keyList_setList(void* ptr, int i);
void* PersonModel3419f1_____roles_keyList_newList(void* ptr);
int PersonModel3419f1_____setRoles_roles_keyList_atList(void* ptr, int i);
void PersonModel3419f1_____setRoles_roles_keyList_setList(void* ptr, int i);
void* PersonModel3419f1_____setRoles_roles_keyList_newList(void* ptr);
int PersonModel3419f1_____rolesChanged_roles_keyList_atList(void* ptr, int i);
void PersonModel3419f1_____rolesChanged_roles_keyList_setList(void* ptr, int i);
void* PersonModel3419f1_____rolesChanged_roles_keyList_newList(void* ptr);
void* PersonModel3419f1_NewPersonModel(void* parent);
void PersonModel3419f1_DestroyPersonModel(void* ptr);
void PersonModel3419f1_DestroyPersonModelDefault(void* ptr);
char PersonModel3419f1_DropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
long long PersonModel3419f1_FlagsDefault(void* ptr, void* index);
void* PersonModel3419f1_IndexDefault(void* ptr, int row, int column, void* parent);
void* PersonModel3419f1_SiblingDefault(void* ptr, int row, int column, void* idx);
void* PersonModel3419f1_BuddyDefault(void* ptr, void* index);
char PersonModel3419f1_CanDropMimeDataDefault(void* ptr, void* data, long long action, int row, int column, void* parent);
char PersonModel3419f1_CanFetchMoreDefault(void* ptr, void* parent);
int PersonModel3419f1_ColumnCountDefault(void* ptr, void* parent);
void* PersonModel3419f1_DataDefault(void* ptr, void* index, int role);
void PersonModel3419f1_FetchMoreDefault(void* ptr, void* parent);
char PersonModel3419f1_HasChildrenDefault(void* ptr, void* parent);
void* PersonModel3419f1_HeaderDataDefault(void* ptr, int section, long long orientation, int role);
char PersonModel3419f1_InsertColumnsDefault(void* ptr, int column, int count, void* parent);
char PersonModel3419f1_InsertRowsDefault(void* ptr, int row, int count, void* parent);
struct Moc_PackedList PersonModel3419f1_ItemDataDefault(void* ptr, void* index);
struct Moc_PackedList PersonModel3419f1_MatchDefault(void* ptr, void* start, int role, void* value, int hits, long long flags);
void* PersonModel3419f1_MimeDataDefault(void* ptr, void* indexes);
struct Moc_PackedString PersonModel3419f1_MimeTypesDefault(void* ptr);
char PersonModel3419f1_MoveColumnsDefault(void* ptr, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
char PersonModel3419f1_MoveRowsDefault(void* ptr, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
void* PersonModel3419f1_ParentDefault(void* ptr, void* index);
char PersonModel3419f1_RemoveColumnsDefault(void* ptr, int column, int count, void* parent);
char PersonModel3419f1_RemoveRowsDefault(void* ptr, int row, int count, void* parent);
void PersonModel3419f1_ResetInternalDataDefault(void* ptr);
void PersonModel3419f1_RevertDefault(void* ptr);
struct Moc_PackedList PersonModel3419f1_RoleNamesDefault(void* ptr);
int PersonModel3419f1_RowCountDefault(void* ptr, void* parent);
char PersonModel3419f1_SetDataDefault(void* ptr, void* index, void* value, int role);
char PersonModel3419f1_SetHeaderDataDefault(void* ptr, int section, long long orientation, void* value, int role);
char PersonModel3419f1_SetItemDataDefault(void* ptr, void* index, void* roles);
void PersonModel3419f1_SortDefault(void* ptr, int column, long long order);
void* PersonModel3419f1_SpanDefault(void* ptr, void* index);
char PersonModel3419f1_SubmitDefault(void* ptr);
long long PersonModel3419f1_SupportedDragActionsDefault(void* ptr);
long long PersonModel3419f1_SupportedDropActionsDefault(void* ptr);
void PersonModel3419f1_ChildEventDefault(void* ptr, void* event);
void PersonModel3419f1_ConnectNotifyDefault(void* ptr, void* sign);
void PersonModel3419f1_CustomEventDefault(void* ptr, void* event);
void PersonModel3419f1_DeleteLaterDefault(void* ptr);
void PersonModel3419f1_DisconnectNotifyDefault(void* ptr, void* sign);
char PersonModel3419f1_EventDefault(void* ptr, void* e);
char PersonModel3419f1_EventFilterDefault(void* ptr, void* watched, void* event);
;
void PersonModel3419f1_TimerEventDefault(void* ptr, void* event);
void QmlBridge3419f1_ConnectSendToQml(void* ptr, long long t);
void QmlBridge3419f1_DisconnectSendToQml(void* ptr);
void QmlBridge3419f1_SendToQml(void* ptr, struct Moc_PackedString source, struct Moc_PackedString action, struct Moc_PackedString data);
void QmlBridge3419f1_SendToGo(void* ptr, struct Moc_PackedString source, struct Moc_PackedString action, struct Moc_PackedString data);
void QmlBridge3419f1_RegisterToGo(void* ptr, void* object);
void QmlBridge3419f1_DeregisterToGo(void* ptr, struct Moc_PackedString objectName);
int QmlBridge3419f1_QmlBridge3419f1_QRegisterMetaType();
int QmlBridge3419f1_QmlBridge3419f1_QRegisterMetaType2(char* typeName);
int QmlBridge3419f1_QmlBridge3419f1_QmlRegisterType();
int QmlBridge3419f1_QmlBridge3419f1_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
int QmlBridge3419f1_QmlBridge3419f1_QmlRegisterUncreatableType(char* uri, int versionMajor, int versionMinor, char* qmlName, struct Moc_PackedString message);
void* QmlBridge3419f1___children_atList(void* ptr, int i);
void QmlBridge3419f1___children_setList(void* ptr, void* i);
void* QmlBridge3419f1___children_newList(void* ptr);
void* QmlBridge3419f1___dynamicPropertyNames_atList(void* ptr, int i);
void QmlBridge3419f1___dynamicPropertyNames_setList(void* ptr, void* i);
void* QmlBridge3419f1___dynamicPropertyNames_newList(void* ptr);
void* QmlBridge3419f1___findChildren_atList(void* ptr, int i);
void QmlBridge3419f1___findChildren_setList(void* ptr, void* i);
void* QmlBridge3419f1___findChildren_newList(void* ptr);
void* QmlBridge3419f1___findChildren_atList3(void* ptr, int i);
void QmlBridge3419f1___findChildren_setList3(void* ptr, void* i);
void* QmlBridge3419f1___findChildren_newList3(void* ptr);
void* QmlBridge3419f1_NewQmlBridge(void* parent);
void QmlBridge3419f1_DestroyQmlBridge(void* ptr);
void QmlBridge3419f1_DestroyQmlBridgeDefault(void* ptr);
void QmlBridge3419f1_ChildEventDefault(void* ptr, void* event);
void QmlBridge3419f1_ConnectNotifyDefault(void* ptr, void* sign);
void QmlBridge3419f1_CustomEventDefault(void* ptr, void* event);
void QmlBridge3419f1_DeleteLaterDefault(void* ptr);
void QmlBridge3419f1_DisconnectNotifyDefault(void* ptr, void* sign);
char QmlBridge3419f1_EventDefault(void* ptr, void* e);
char QmlBridge3419f1_EventFilterDefault(void* ptr, void* watched, void* event);
;
void QmlBridge3419f1_TimerEventDefault(void* ptr, void* event);

#ifdef __cplusplus
}
#endif

#endif